#generated by MCBuilder/mc

scoreboard players set playing lobby_stats 0
scoreboard players set unassigned lobby_stats 0
scoreboard players set spectating lobby_stats 0
execute as @a[team=playing] run scoreboard players add playing lobby_stats 1
execute as @a[team=spectating] run scoreboard players add spectating lobby_stats 1
execute as @a unless entity @s[team=playing] unless entity @s[team=spectating] run scoreboard players add unassigned lobby_stats 1
execute store result score difficulty game_config run data get entity @e[tag=difficulty-selector,limit=1] ItemRotation 1
execute if score difficulty game_config matches 0 run data modify entity @e[tag=difficulty-display,limit=1] CustomName set value '[{"text": "Easy","color":"green"}]'
execute if score difficulty game_config matches 1 run data modify entity @e[tag=difficulty-display,limit=1] CustomName set value '[{"text": "Medium","color":"yellow"}]'
execute if score difficulty game_config matches 2 run data modify entity @e[tag=difficulty-display,limit=1] CustomName set value '[{"text": "Hard","color":"red"}]'
execute if score difficulty game_config matches 3 run data modify entity @e[tag=difficulty-display,limit=1] CustomName set value '[{"text": "Extra Hard","color":"dark_red"}]'
execute if score difficulty game_config matches 4 run data modify entity @e[tag=difficulty-display,limit=1] CustomName set value '[{"text": "Challenge","color":"gold"}]'
execute if score difficulty game_config matches 5 run data modify entity @e[tag=difficulty-display,limit=1] CustomName set value '[{"text": "reserved for future update!","color":""}]'
execute if score difficulty game_config matches 6 run data modify entity @e[tag=difficulty-display,limit=1] CustomName set value '[{"text": "reserved for future update!","color":""}]'
execute if score difficulty game_config matches 7 run data modify entity @e[tag=difficulty-display,limit=1] CustomName set value '[{"text": "reserved for future update!","color":""}]'